export function shortenNumbers (str) {
  return str
  .replace('première', '1ère')
  .replace('deuxième', '2ème')
  .replace('troisième', '3ème')
  .replace('quatrième', '4ème')
  .replace('cinquième', '5ème')
  .replace('sixième', '6ème')
  .replace('septième', '7ème')
  .replace('huitième', '8ème')
  .replace('neuvième', '9ème')
  .replace('dixième', '10ème')
  .replace('onzième', '11ème')
  .replace('douzième', '12ème')
  .replace('treizième', '13ème')
  .replace('quatorzième', '14ème')
  .replace('quinzième', '15ème')
  .replace('seizième', '16ème')
  .replace('dix-septième', '17ème')
  .replace('dix-huitième', '18ème')
  .replace('dix-neuvième', '19ème')
  .replace('vingtième', '20ème')
  .replace('vingt et unième', '21ème')
}
